source 'http://rubygems.org'

gem 'clamp'
gem 'rack'
gem 'json'
gem 'thin'
gem 'aws-sdk'
gem 'mail'
gem 'eventmachine'
gem 'mongoid'
gem 'sinatra'
gem 'kaminari', :require => 'kaminari/sinatra'
gem 'padrino-helpers'