source 'http://rubygems.org'

gem 'clamp'
gem 'rack'
gem 'json'
gem 'thin'
gem 'aws-sdk', '< 2'
gem 'mail'
gem 'eventmachine'
gem 'mongoid'
gem 'haml'
gem 'sinatra'
gem 'kaminari', :require => 'kaminari/sinatra'
gem 'padrino-helpers'
gem 'daemons'
gem 'actionpack', '3.2.16'